{% set name = "pyiceberg" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiceberg-{{ version }}.tar.gz
  sha256: 0ef2216d0c0d569b8574f48698c331e051f8276a6e1090aa75c2e098ea5aa286

build:
  entry_points:
    - pyiceberg = pyiceberg.cli.console:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry
  run:
    - python >=3.7,<4.0
    - click >=8.1.3,<9.0.0
    - fsspec >=2022.8.2
    - mmh3 >=3.0.0,<4.0.0     # pip uses mmhash3
    - pyarrow
    - pydantic >=1.10.2,<2.0.0
    - pyyaml >=6.0.0,<7.0.0
    - requests >=2.28.1,<3.0.0
    - rich >=12.5.1,<13.0.0
    - zstandard >=0.18.0,<0.19.0

test:
  imports:
    - fb303
    - hive_metastore
    - pyiceberg
  commands:
#    - pip check
    - pyiceberg --help
  requires:
    - pip

about:
  home: https://iceberg.apache.org/
  summary: Apache Iceberg is an open table format for huge analytic datasets
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
