# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: pyiceberg
  version: "0.9.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyiceberg-${{ version }}.tar.gz
  sha256: 3634134ce33859a441768b39df179b2c6f3de2bbbf506622884f553b013ee799

build:
  number: 2
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pyiceberg = pyiceberg.cli.console:run

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython >=3.0.0
        - numpy
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - poetry-core >=1.0.0
    - wheel
    - cython >=3.0.0
    - numpy
    - setuptools
    - pip
  run:
    - python
    - mmh3 >=4.0.0,<6.0.0
    - requests >=2.20.0,<3.0.0
    - click >=7.1.1,<9.0.0
    - rich >=10.11.0,<14.0.0
    - strictyaml >=1.7.0,<2.0.0
    - pydantic >=2.0,<3.0,!=2.4.0,!=2.4.1  # 2.4.0, 2.4.1 has a critical bug
    - sortedcontainers 2.4.0.*
    - fsspec >=2023.1.0
    - pyparsing >=3.1.0,<4.0.0
    - zstandard >=0.13.0,<1.0.0
    - tenacity >=8.2.3,<10.0.0
    - cachetools >=5.5.0,<6.0.0
  run_constraints:
    # https://github.com/apache/iceberg-python/blob/main/pyproject.toml#L60C1-L60C59
    - pyarrow >=17.0.0,<20.0.0
    - pandas >=1.0.0,<3.0.0
    - python-duckdb >=0.5.0,<2.0.0
    - ray >=2.10.0,<3.0.0
    - python-snappy >=0.6.0,<1.0.0
    - thrift >=0.13.0,<1.0.0
    - mypy-boto3-glue >=1.28.18
    - boto3 >=1.24.59
    - s3fs >=2023.1.0
    - adlfs >=2023.1.0
    - gcsfs >=2023.1.0
    - psycopg2-binary >=2.9.6
    - sqlalchemy >=2.0.18,<3.0.0
    - getdaft >=0.2.12
    #- pyiceberg-core >=0.4.0,<0.5.0
    - polars >=1.21.0,<2.0.0
    #- thrift-sasl >=0.4.3
    #- kerberos >=1.3.1,<2.0.0

tests:
  - python:
      imports:
        - fb303
        - hive_metastore
        - pyiceberg
        - pyiceberg.avro.decoder_fast # Test compiled module
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - pyiceberg --help

about:
  summary: Apache Iceberg is an open table format for huge analytic datasets
  homepage: https://iceberg.apache.org/
  description: |
    "Iceberg is a high-performance format for huge analytic tables.
    Iceberg brings the reliability and simplicity of SQL tables to big data, while making it possible for engines like 
    Spark, Trino, Flink, Presto, Hive and Impala to safely work with the same tables, at the same time."
  repository: https://github.com/apache/iceberg
  documentation: https://iceberg.apache.org/docs/nightly/
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - rxm7706
